APBox/Controllers/Operaciones/DocumentosExtranjerosController.cs
using APBox.Context;
using API.Operaciones.Facturacion;
using CFDI.API.Enums.CFDI33;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace APBox.Controllers.Operaciones
{
    public class DocumentosExtranjerosController : Controller
    {
        #region Variables

        private readonly APBoxContext _db = new APBoxContext();

        #endregion

        // GET: DocumentosExtranjeros
        public ActionResult Index()
        {
            var documentosExtranjeros = _db.DocumentosExtranjeros.ToList();
            return View(documentosExtranjeros);
        }

        // GET: DocumentosExtranjeros/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocumentoExtranjero documentoExtranjero = _db.DocumentosExtranjeros.Find(id);
            if (documentoExtranjero == null)
            {
                return HttpNotFound();
            }
            return View(documentoExtranjero);
        }

        // GET: DocumentosExtranjeros/Create
        public ActionResult Create()
        {
            var documentoExtranjero = new DocumentoExtranjero
            {
                UsuarioId = ObtenerUsuario(),
                Fecha = DateTime.Now,
                Moneda = c_Moneda.USD,
                TipoCambio = 1,
                ReceptorId = ObtenerSucursal(),
                TipoGasto = API.Enums.TiposGastos.Personal
            };

            return View(documentoExtranjero);
        }

        // POST: DocumentosExtranjeros/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DocumentoExtranjero documentoExtranjero)
        {
            if (ModelState.IsValid)
            {
                _db.DocumentosExtranjeros.Add(documentoExtranjero);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(documentoExtranjero);
        }

        // GET: DocumentosExtranjeros/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocumentoExtranjero documentoExtranjero = _db.DocumentosExtranjeros.Find(id);
            if (documentoExtranjero == null)
            {
                return HttpNotFound();
            }
            return View(documentoExtranjero);
        }

        // POST: DocumentosExtranjeros/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DocumentoExtranjero documentoExtranjero)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(documentoExtranjero).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(documentoExtranjero);
        }

        // GET: DocumentosExtranjeros/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocumentoExtranjero documentoExtranjero = _db.DocumentosExtranjeros.Find(id);
            if (documentoExtranjero == null)
            {
                return HttpNotFound();
            }
            return View(documentoExtranjero);
        }

        // POST: DocumentosExtranjeros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DocumentoExtranjero documentoExtranjero = _db.DocumentosExtranjeros.Find(id);
            _db.DocumentosExtranjeros.Remove(documentoExtranjero);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Popula Forma

        private int ObtenerSucursal()
        {
            return Convert.ToInt32(Session["SucursalId"]);
        }

        private int ObtenerUsuario()
        {
            return Convert.ToInt32(Session["UsuarioId"]);
        }

        #endregion

    }
}

APBox/Views/DocumentosExtranjeros/Create.cshtml
@model API.Operaciones.Facturacion.DocumentoExtranjero

@{
    ViewBag.Title = "Crear";
    ViewBag.Clase = "Documento Extranjero";
}

<div id="page-title">
    <h2>@ViewBag.Title - @ViewBag.Clase</h2>
</div>
<div class="panel">
    <div class="panel-body">
        @using (Html.BeginForm("Create", "DocumentosExtranjeros", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
        <div class="form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.Fecha)
            @Html.HiddenFor(model => model.ReceptorId)
            @Html.HiddenFor(model => model.UsuarioId)
            @Html.HiddenFor(model => model.TipoGasto)

            @Html.HiddenFor(model => model.Autorizada)
            @Html.HiddenFor(model => model.FechaAutorizacion)
            @Html.HiddenFor(model => model.NotasAutorizacion)
            @Html.HiddenFor(model => model.UsuarioAutorizacionId)

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Información
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                @Html.LabelFor(model => model.NombreEmisor, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.NombreEmisor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreEmisor, "", new { @class = "text-danger" })
            </div>

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Información
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.Moneda, htmlAttributes: new { @class = "control-label" })
                @Html.EnumDropDownListSpecialFor(model => model.Moneda)
                @Html.ValidationMessageFor(model => model.Moneda, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.TipoCambio, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.TipoCambio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoCambio, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                @Html.LabelFor(model => model.Concepto, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Concepto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Concepto, "", new { @class = "text-danger" })
            </div>

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Archivo
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label class="control-label">Seleccionar Archivo</label>
                <input type="file" name="FileUpload" id="file" class="minusculas">
            </div>


            <div class="clearfix"></div>
            <hr />
            <div class="form-group pull-right">
                <button class="btn btn-alt btn-hover btn-default" onclick="location.href='@Url.Action("Index")';return false;">
                    <span>Regresar</span>
                    <i class="glyph-icon icon-arrow-left"></i>
                </button>
                <button type="submit" class="btn btn-alt btn-hover btn-blue-alt">
                    <span>Crear</span>
                    <i class="glyph-icon icon-arrow-right"></i>
                </button>
            </div>
        </div>
        }
    </div>
</div>

APBox/Views/DocumentosExtranjeros/Delete.cshtml
@model API.Operaciones.Facturacion.DocumentoExtranjero

@{
    ViewBag.Title = "Eliminar";
    ViewBag.Clase = "Documento Extranjero";
}

<h3 class="alert alert-danger">¿Está seguro que desea eliminar este registro?</h3>

<div id="page-title">
    <h2>@ViewBag.Title - @ViewBag.Clase</h2>
</div>
<div class="panel">
    <div class="panel-body">
        @using (Html.BeginForm("Delete", "DocumentosExtranjeros", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
        <div class="form deshabilitar">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.Id)

            @Html.HiddenFor(model => model.Fecha)
            @Html.HiddenFor(model => model.ReceptorId)
            @Html.HiddenFor(model => model.UsuarioId)
            @Html.HiddenFor(model => model.TipoGasto)

            @Html.HiddenFor(model => model.Autorizada)
            @Html.HiddenFor(model => model.FechaAutorizacion)
            @Html.HiddenFor(model => model.NotasAutorizacion)
            @Html.HiddenFor(model => model.UsuarioAutorizacionId)

            @Html.HiddenFor(model => model.NombreArchivo)
            @Html.HiddenFor(model => model.Archivo)

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Información
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                @Html.LabelFor(model => model.NombreEmisor, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.NombreEmisor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreEmisor, "", new { @class = "text-danger" })
            </div>

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Información
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.Moneda, htmlAttributes: new { @class = "control-label" })
                @Html.EnumDropDownListSpecialFor(model => model.Moneda)
                @Html.ValidationMessageFor(model => model.Moneda, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.TipoCambio, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.TipoCambio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoCambio, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                @Html.LabelFor(model => model.Concepto, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Concepto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Concepto, "", new { @class = "text-danger" })
            </div>

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Archivo
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label class="control-label">Seleccionar Archivo</label>
                <input type="file" name="FileUpload" id="file" class="minusculas">
            </div>


            <div class="clearfix"></div>
            <hr />
            <div class="form-group pull-right">
                <button class="btn btn-alt btn-hover btn-default" onclick="location.href='@Url.Action("Index")';return false;">
                    <span>Regresar</span>
                    <i class="glyph-icon icon-arrow-left"></i>
                </button>
                <button type="submit" class="btn btn-alt btn-hover btn-blue-alt">
                    <span>Eliminar</span>
                    <i class="glyph-icon icon-arrow-right"></i>
                </button>
            </div>
        </div>
        }
    </div>
</div>

APBox/Views/DocumentosExtranjeros/Details.cshtml
@model API.Operaciones.Facturacion.DocumentoExtranjero

@{
    ViewBag.Title = "Detalles";
    ViewBag.Clase = "Documento Extranjero";
}

<div id="page-title">
    <h2>@ViewBag.Title - @ViewBag.Clase</h2>
</div>
<div class="panel">
    <div class="panel-body">
        @using (Html.BeginForm("Delete", "DocumentosExtranjeros", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
        <div class="form deshabilitar">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.Id)

            @Html.HiddenFor(model => model.Fecha)
            @Html.HiddenFor(model => model.ReceptorId)
            @Html.HiddenFor(model => model.UsuarioId)
            @Html.HiddenFor(model => model.TipoGasto)

            @Html.HiddenFor(model => model.Autorizada)
            @Html.HiddenFor(model => model.FechaAutorizacion)
            @Html.HiddenFor(model => model.NotasAutorizacion)
            @Html.HiddenFor(model => model.UsuarioAutorizacionId)

            @Html.HiddenFor(model => model.NombreArchivo)
            @Html.HiddenFor(model => model.Archivo)

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Información
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                @Html.LabelFor(model => model.NombreEmisor, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.NombreEmisor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreEmisor, "", new { @class = "text-danger" })
            </div>

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Información
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.Moneda, htmlAttributes: new { @class = "control-label" })
                @Html.EnumDropDownListSpecialFor(model => model.Moneda)
                @Html.ValidationMessageFor(model => model.Moneda, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.TipoCambio, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.TipoCambio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoCambio, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                @Html.LabelFor(model => model.Concepto, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Concepto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Concepto, "", new { @class = "text-danger" })
            </div>

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Archivo
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label class="control-label">Seleccionar Archivo</label>
                <input type="file" name="FileUpload" id="file" class="minusculas">
            </div>


            <div class="clearfix"></div>
            <hr />
            <div class="form-group pull-right">
                <button class="btn btn-alt btn-hover btn-default" onclick="location.href='@Url.Action("Index")';return false;">
                    <span>Regresar</span>
                    <i class="glyph-icon icon-arrow-left"></i>
                </button>
                <button class="btn btn-alt btn-hover btn-blue-alt" onclick="location.href='@Url.Action("Edit", new { @id = Model.Id })';return false;">
                    <span>Editar</span>
                    <i class="glyph-icon icon-arrow-right"></i>
                </button>
            </div>
        </div>
        }
    </div>
</div>

APBox/Views/DocumentosExtranjeros/Edit.cshtml
@model API.Operaciones.Facturacion.DocumentoExtranjero

@{
    ViewBag.Title = "Editar";
    ViewBag.Clase = "Documento Extranjero";
}

<div id="page-title">
    <h2>@ViewBag.Title - @ViewBag.Clase</h2>
</div>
<div class="panel">
    <div class="panel-body">
        @using (Html.BeginForm("Edit", "DocumentosExtranjeros", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
        <div class="form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.Id)

            @Html.HiddenFor(model => model.Fecha)
            @Html.HiddenFor(model => model.ReceptorId)
            @Html.HiddenFor(model => model.UsuarioId)
            @Html.HiddenFor(model => model.TipoGasto)

            @Html.HiddenFor(model => model.Autorizada)
            @Html.HiddenFor(model => model.FechaAutorizacion)
            @Html.HiddenFor(model => model.NotasAutorizacion)
            @Html.HiddenFor(model => model.UsuarioAutorizacionId)

            @Html.HiddenFor(model => model.NombreArchivo)
            @Html.HiddenFor(model => model.Archivo)

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Información
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                @Html.LabelFor(model => model.NombreEmisor, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.NombreEmisor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreEmisor, "", new { @class = "text-danger" })
            </div>

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Información
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.Moneda, htmlAttributes: new { @class = "control-label" })
                @Html.EnumDropDownListSpecialFor(model => model.Moneda)
                @Html.ValidationMessageFor(model => model.Moneda, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.TipoCambio, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.TipoCambio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoCambio, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-6 col-md-4 col-lg-4">
                @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                @Html.LabelFor(model => model.Concepto, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Concepto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Concepto, "", new { @class = "text-danger" })
            </div>

            <div class="clearfix"></div>

            <div class="sub-title">
                <span class="fa fa-bars text-muted"></span> Archivo
            </div>

            <hr />

            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label class="control-label">Seleccionar Archivo</label>
                <input type="file" name="FileUpload" id="file" class="minusculas">
            </div>


            <div class="clearfix"></div>
            <hr />
            <div class="form-group pull-right">
                <button class="btn btn-alt btn-hover btn-default" onclick="location.href='@Url.Action("Index")';return false;">
                    <span>Regresar</span>
                    <i class="glyph-icon icon-arrow-left"></i>
                </button>
                <button type="submit" class="btn btn-alt btn-hover btn-blue-alt">
                    <span>Guardar</span>
                    <i class="glyph-icon icon-arrow-right"></i>
                </button>
            </div>
        </div>
        }
    </div>
</div>

APBox/Views/DocumentosExtranjeros/Index.cshtml
@model IEnumerable<API.Operaciones.Facturacion.DocumentoExtranjero>

@{
    ViewBag.Title = "Documentos Extranjeros";
}

<div id="page-title">
    <div class="row">
        <div class="col-lg-9">
            <h2>@ViewBag.Title</h2>
        </div>
        <div class="col-lg-3">
            <button type="submit" class="btn btn-alt btn-hover btn-primary float-right" onclick="location.href='@Url.Action("Create")';return false;">
                <span>[ Nuevo Registro ]</span>
                <i class="glyph-icon icon-arrow-right"></i>
            </button>
        </div>
    </div>
</div>
<div class="panel">
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <table class="dataTable">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.NombreEmisor)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Fecha)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Moneda)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TipoCambio)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Total)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Concepto)
                            </th>
                            <th>
                                Opciones
                            </th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.NombreEmisor)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Fecha)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Moneda)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TipoCambio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Total)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Concepto)
                            </td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="fa fa-cog"></span> Opciones
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li>@Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "edit" })</li>
                                        <li>@Html.ActionLink("Detalles", "Details", new { id = item.Id }, new { @class = "details" })</li>
                                        <li>@Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "delete" })</li>
                                    </ul>
                                </div>
                            </td>

                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
</div>