APBox/Controllers/Ajax/AjaxCatalogosController.cs
using APBox.Context;
using API.Models.Dto;
using API.Relaciones;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace InventorAid.Controllers.Ajax
{
    public class AjaxCatalogosController : Controller
    {

        #region Variables

        private readonly APBoxContext _db = new APBoxContext();

        #endregion

        public PartialViewResult SucursalesUsuarios(int sucursalId)
        {
            var usuarioSucursal = new UsuarioSucursal
            {
                SucursalId = sucursalId,
                Sucursal = _db.Sucursales.Find(sucursalId)
            };

            return PartialView("~/Views/Usuarios/Sucursales.cshtml", usuarioSucursal);
        }

        public PartialViewResult SucursalesProveedores(int sucursalId)
        {
            var proveedorSucursal = new ProveedorSucursal
            {
                SucursalId = sucursalId,
                Sucursal = _db.Sucursales.Find(sucursalId)
            };

            return PartialView("~/Views/Proveedores/Sucursales.cshtml", proveedorSucursal);
        }

        public PartialViewResult BancosClientes(int bancoId, string nombre, string numeroCuenta)
        {
            var bancoCliente = new BancoCliente
            {
                BancoId = bancoId,
                Banco = _db.Bancos.Find(bancoId),
                Nombre = nombre,
                NumeroCuenta = numeroCuenta
            };

            return PartialView("~/Views/Clientes/Bancos.cshtml", bancoCliente);
        }

        public PartialViewResult BancosSucursales(int bancoId, string nombre, string numeroCuenta)
        {
            var bancoSucursal = new BancoSucursal
            {
                BancoId = bancoId,
                Banco = _db.Bancos.Find(bancoId),
                Nombre = nombre,
                NumeroCuenta = numeroCuenta
            };

            return PartialView("~/Views/Sucursales/Bancos.cshtml", bancoSucursal);
        }

        #region Popular DropDowns

        public JsonResult GetSucursales(int grupoId)
        {
            var sucursales = _db.Sucursales.Where(s => s.GrupoId == grupoId).OrderBy(s => s.Nombre).ToList();

            foreach (var sucursal in sucursales)
            {
                sucursal.Grupo = null;

                if(sucursal.Bancos != null)
                {
                    sucursal.Bancos.Clear();
                    sucursal.Bancos = null;
                }
                sucursal.Banco = null;

                sucursal.ArchivoCer = null;
                sucursal.Cer = null;
                sucursal.ArchivoKey = null;
                sucursal.Key = null;
                sucursal.ArchivoLogo = null;
                sucursal.Logo = null;
            }

            return Json(sucursales, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBancosClientes(int clienteId)
        {
            var bancosClientes = _db.BancosClientes.Where(s => s.ClienteId == clienteId).OrderBy(s => s.Nombre).ToList();

            foreach (var banco in bancosClientes)
            {
                banco.Cliente.Sucursal = new API.Catalogos.Sucursal();
                
                if(banco.Cliente.Bancos != null)
                {
                    banco.Cliente.Bancos.Clear();
                    banco.Cliente.Bancos = null;
                }
            }

            return Json(bancosClientes, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCfdisCancelados(int clienteId)
        {
            var cfdis = _db.ComplementosPago.Where(f => f.ReceptorId == clienteId  && f.FacturaEmitidaId != null).ToList();

            foreach (var cfdi in cfdis)
            {

                cfdi.FacturaEmitida.ArchivoFisicoXml = null;
                cfdi.FacturaEmitida.CodigoQR = null;
                cfdi.FacturaEmitida.Emisor.Bancos.Clear();
                cfdi.FacturaEmitida.Emisor.Cer = null;
                cfdi.FacturaEmitida.Emisor.Key = null;
                cfdi.FacturaEmitida.Emisor.Grupo = null;
                cfdi.FacturaEmitida.Emisor.Logo = null;

                cfdi.FacturaEmitida.Receptor.Bancos.Clear();
                cfdi.FacturaEmitida.Receptor.Sucursal = null;

                cfdi.FacturaEmitida.CentroCosto = null;
                cfdi.FacturaEmitida.ComplementosPago.Clear();
                cfdi.FacturaEmitida.ComplementosPago = null;
                cfdi.FacturaEmitida.Departamento = null;

                cfdi.Pagos.Clear();
                cfdi.Pagos = null;
                cfdi.Receptor = null;
                cfdi.Sucursal = null;
            }

            return Json(cfdis, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCfdisCanceladosCP(int? clienteId)
        {
            var cfdis = _db.ComplementoCartaPortes.Where(f => f.ReceptorId == clienteId &&  f.FacturaEmitidaId != null && f.Total > 0).ToList();
            
            var ListCfdiR = new List<CfdiRelacionadoDto>();
            foreach (var cfdi in cfdis)
            {
                CfdiRelacionadoDto cfdiR = new CfdiRelacionadoDto 
                {
                    Id = cfdi.FacturaEmitida.Id,
                    Desplegado = cfdi.FacturaEmitida.Desplegado
                };
               
               
                ListCfdiR.Add(cfdiR);
            }
            
            return Json(ListCfdiR, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

APBox/Controllers/Ajax/AjaxOperacionesController.cs
using APBox.Context;
using API.Operaciones.ComplementosPagos;
using API.Operaciones.ComplementoCartaPorte;
using API.CatalogosCartaPorte;
using Aplicacion.LogicaPrincipal.CargasMasivas.CSV;
using CFDI.API.Enums.CFDI33;
using CFDI.API.Enums.Complementos.Pagos10;
using System;
using System.Web.Mvc;
using System.Collections.Generic;
using API.Models.Dto;
using System.Linq;
using API.Enums.CartaPorteEnums;

namespace APBox.Controllers.Ajax
{
    public class AjaxOperacionesController : Controller
    {

        #region Variables

        private readonly APBoxContext _db = new APBoxContext();

        #endregion

        public PartialViewResult AgregarPago(DateTime fechaPago, string formaPago, string moneda, double tipoCambio, double monto, string numeroOperacion, string tipoCadenaPago, string certificadoPago, string cadenaPago, string selloPago, string spei, int? bancoEmisorId, int? bancoReceptorId)
        {
            var pago = new Pago
            {
                BancoOrdenante = _db.BancosClientes.Find(bancoEmisorId),
                BancoOrdenanteId = bancoEmisorId,
                BancoBeneficiario = _db.BancosSucursales.Find(bancoReceptorId),
                BancoBeneficiarioId = bancoReceptorId,
                CadenaPago = cadenaPago,
                FechaPago = fechaPago,
                FormaPago = (c_FormaPago)Enum.Parse(typeof(c_FormaPago), formaPago, true),
                Moneda = (c_Moneda)Enum.Parse(typeof(c_Moneda), moneda, true),
                Monto = monto,
                NumeroOperacion = numeroOperacion,
                TipoCambio = tipoCambio,
                SucursalId = ObtenerSucursal(),
            };

            if (spei != null)
            {
                var pathSpei = String.Format(@"C:/Infodextra/Temp/{0}.xml", DateTime.Now.ToString("ddMMyyyymmssttt"));
                System.IO.File.WriteAllText(pathSpei, spei);

                var operacionesSpei = new OperacionesSpei();
                var xmlSpei = operacionesSpei.Decodificar(pathSpei);

                pago.TipoCadenaPago = c_TipoCadenaPago.Spei;
                pago.CertificadoPago = xmlSpei.numeroCertificado;
                pago.CadenaPago = xmlSpei.cadenaCDA;
                pago.SelloPago = xmlSpei.sello;
            }

            return PartialView("~/Views/ComplementosPagos/Pagos.cshtml", pago);
        }

        public PartialViewResult AgregarFacturaComplementoPago(int pagoId, int facturaEmitidaId, int numeroParcialidad, string moneda, double tipoCambio, double importeSaldoAnterior, double importePagado, double importeSaldoInsoluto)
        {
            var facturaEmitida = _db.FacturasEmitidas.Find(facturaEmitidaId);

            var documentoRelacionado = new DocumentoRelacionado
            {
                FacturaEmitidaId = facturaEmitida.Id,
                FacturaEmitida = facturaEmitida,
                ImportePagado = importePagado,
                ImporteSaldoAnterior = importeSaldoAnterior,
                ImporteSaldoInsoluto = importeSaldoInsoluto,
                NumeroParcialidad = numeroParcialidad,
                Moneda = (c_Moneda)Enum.Parse(typeof(c_Moneda), moneda, true),
                TipoCambio = tipoCambio,
                PagoId = pagoId,

                IdDocumento = facturaEmitida.Uuid,
                Folio = facturaEmitida.Folio.ToString(),
                MetodoPago = c_MetodoPago.PPD,
                Serie = facturaEmitida.Serie
            };

            return PartialView("~/Views/ComplementosPagos/FacturasDetalles.cshtml", documentoRelacionado);
        }

        public PartialViewResult AgregarUbicacion(String TipoUbicacion,
            String TipoEstacion,
            String TipoEstacionId, 
            String IdUbicacion,
         String RFCRemitenteDestinatario,
             String NombreRemitenteDestinatario,
             string NumRegIdTrib,
              String ResidenciaFiscal,
               String NombreEstacion,
                String NumEstacion,
                string NavegacionTrafico,
                DateTime FechaHoraSalidaLlegada,
                Decimal DistanciaRecorrida,
                 String Calle,
                  String CodigoPostal,
                   String Colonia,
                   string ColoniaText,
                   String Estado,
                   string EstadoText,
                    String Localidad,
                    string LocalidadText,
                    String Municipio,
                    string MunicipioText,
                    String NumeroExterior,
                    String NumeroInterior,
                    String Pais,
                    string PaisText,
                    String Referencia)
        {
            c_Pais? ResidenciaFiscalParse=null;
            if (ResidenciaFiscal == "")
            {
                ResidenciaFiscalParse = null;
            }
            else { ResidenciaFiscalParse = (c_Pais)Enum.Parse(typeof(c_Pais), ResidenciaFiscal, true); }
            var Ubicacion = new Ubicacion
            {
                TipoUbicacion = TipoUbicacion,
                TipoEstaciones = TipoEstacion,
                TipoEstacion_Id = TipoEstacionId,
                IDUbicacion = IdUbicacion,
                RfcRemitenteDestinatario = RFCRemitenteDestinatario,
                NombreRemitenteDestinatario = NombreRemitenteDestinatario,
                NumRegIdTrib = NumRegIdTrib,
                ResidenciaFiscal = ResidenciaFiscalParse,
                NombreEstacion = NombreEstacion,
                NumEstacion = NumEstacion,
                Estaciones_Id = NumEstacion,
                NavegacionTrafico= NavegacionTrafico,
                FechaHoraSalidaLlegada = FechaHoraSalidaLlegada,
                DistanciaRecorrida = DistanciaRecorrida,
                Domicilio = new Domicilio()
                {
                    Calle = Calle,
                    CodigoPostal = CodigoPostal,
                    Colonia = Colonia,
                    colonias = ColoniaText,
                    Estado = Estado,
                    estados = EstadoText,
                    Localidad = Localidad,
                    localidades = LocalidadText,
                    Municipio = Municipio,
                    municipios = MunicipioText,
                    NumeroExterior = NumeroExterior,
                    NumeroInterior = NumeroInterior,
                    Pais = Pais,
                    paiss = PaisText,
                    Referencia = Referencia
                }
            };

            return PartialView("~/Views/ComplementosCartaPorte/Ubicacion.cshtml", Ubicacion);
        }

        

        public PartialViewResult AgregarMercancia(String ClaveProdServID, string ClaveProdSTCCID,string Descripcion,
            int Cantidad,string Unidad,string ClaveUnidadID,string Dimensiones,bool MaterialPeligorosoSN, 
            string MaterialPeligrosoID, string DescripcionEmbalaje, string TipoEmbalajeID,Decimal PesoEnKg,string ValorMercancia,
            string Moneda, string FraccionArancelariaID, string UUIDComercioExt,
            string DEClaveUnidadPesoID, Decimal DEPesoBruto, Decimal DEPEsoNeto,Decimal DEPesoTara, int DENumPiezas,
            List<Pedimentos> PedimentoArray, List<GuiasIdentificacion> GIdentificacionArray, List<CantidadTransportada> CTransportadaArray)
        {
            
            var mercancia = new Mercancia()
            {
                ClaveProdServCP = ClaveProdServID,
                ClaveProdSTCC = ClaveProdSTCCID,
                Descripcion = Descripcion,
                Cantidad = Cantidad,
                Unidad = Unidad,
                ClavesUnidad = ClaveUnidadID,
                Dimensiones = Dimensiones,
                MaterialPeligrosos = MaterialPeligorosoSN,
                ClaveMaterialPeligroso = MaterialPeligrosoID,
                DescripEmbalaje = DescripcionEmbalaje,
                TipoEmbalaje_Id = TipoEmbalajeID,
                PesoEnKg = PesoEnKg,
                ValorMercancia = ValorMercancia,
                Moneda = (c_Moneda)Enum.Parse(typeof(c_Moneda), Moneda, true), 
                FraccionArancelarias= FraccionArancelariaID,
                UUIDComecioExt = UUIDComercioExt,
                DetalleMercancia = new DetalleMercancia()
                {
                    ClaveUnidadPeso_Id = DEClaveUnidadPesoID,
                    PesoBruto = DEPesoBruto,
                    PesoNeto = DEPEsoNeto,
                    PesoTara = DEPesoTara,
                    NumPiezas = DENumPiezas
                }
                
            };
            if (PedimentoArray != null)
            {
                mercancia.Pedimentoss = new List<Pedimentos>();
                foreach(var ped in PedimentoArray)
                {
                    mercancia.Pedimentoss.Add(ped);
                }
            }
            if (GIdentificacionArray != null)
            {
                mercancia.GuiasIdentificacionss = new List<GuiasIdentificacion>();
                foreach(var GIdent in GIdentificacionArray)
                {
                    mercancia.GuiasIdentificacionss.Add(GIdent);
                }
            }
            if (CTransportadaArray != null)
            {
                mercancia.CantidadTransportadass = new List<CantidadTransportada>();
                foreach(var CTrans in CTransportadaArray)
                {
                    mercancia.CantidadTransportadass.Add(CTrans);
                }
            }
            return PartialView("~/Views/ComplementosCartaPorte/Mercancia.cshtml", mercancia);
        }

        public PartialViewResult AgregarMercanciaEdit(String ClaveProdServID, string ClaveProdSTCCID, string Descripcion,
            int Cantidad, string Unidad, string ClaveUnidadID, string Dimensiones, bool MaterialPeligorosoSN,
            string MaterialPeligrosoID, string DescripcionEmbalaje, string TipoEmbalajeID, Decimal PesoEnKg, string ValorMercancia,

APBox/Views/ComplementosPagos/FacturasDetalles.cshtml
@model API.Operaciones.ComplementosPagos.DocumentoRelacionado

@using (Html.BeginCollectionItem("DocumentosRelacionados"))
    {
    @Html.ValidationSummary(true, "", new { @class = "label-blue-alt" })

    <div class="content-box mrg20L mrg20R">
        <h4 class="content-box-header bg-default">
            <i class="glyph-icon fas fa-file"></i>
            <b>Doc Relacionado</b>
            <span>
                - Serie / Folio: <b>@Model.Serie - @Model.Folio</b>
                - UUID: <b>@Model.IdDocumento</b>
                - Método Pago: <b>@Model.MetodoPago</b>
            </span>

            <div class="header-buttons-separator">
                <a href="#" class="icon-separator" onclick="$(this).parent().parent().parent().remove();">
                    <i class="glyph-icon icon-times font-red"></i>
                </a>
            </div>
        </h4>
        <div class="content-box-wrapper pago">
            <div class="col-xs-12 col-sm-2">
                <b>Moneda</b><br />
                @Html.DisplayFor(model => model.Moneda)
            </div>

            <div class="col-xs-12 col-sm-2">
                <b>TC o Factor</b><br />
                @Html.DisplayFor(model => model.TipoCambio)
            </div>

            <div class="col-xs-12 col-sm-2">
                <b>Numero Parcialidad</b><br />
                @Html.DisplayFor(model => model.NumeroParcialidad)
            </div>

            <div class="col-xs-12 col-sm-2">
                <b>Imp Saldo Anterior</b><br />
                @Model.ImporteSaldoAnterior.Value.ToString("c")
            </div>

            <div class="col-xs-12 col-sm-2">
                <b>Imp Pagado</b><br />
                @Model.ImportePagado.Value.ToString("c")
            </div>

            <div class="col-xs-12 col-sm-2">
                <b>Imp Saldo Insoluto</b><br />
                @Model.ImporteSaldoInsoluto.Value.ToString("c")
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.FacturaEmitidaId)
    @Html.HiddenFor(model => model.FacturaEmitida.Subtotal)
    @Html.HiddenFor(model => model.FacturaEmitida.Total)
    @Html.HiddenFor(model => model.ImportePagado)
    @Html.HiddenFor(model => model.ImporteSaldoAnterior)
    @Html.HiddenFor(model => model.ImporteSaldoInsoluto)
    @Html.HiddenFor(model => model.MetodoPago)
    @Html.HiddenFor(model => model.Moneda)
    @Html.HiddenFor(model => model.NumeroParcialidad)
    @Html.HiddenFor(model => model.PagoId)
    @Html.HiddenFor(model => model.TipoCambio)
    @Html.HiddenFor(model => model.Serie)
    @Html.HiddenFor(model => model.Folio)
    @Html.HiddenFor(model => model.IdDocumento)

    }

APBox/Views/ComplementosPagos/Pagos.cshtml
@model API.Operaciones.ComplementosPagos.Pago

@using (Html.BeginCollectionItem("Pagos"))
    {
    @Html.ValidationSummary(true, "", new { @class = "label-blue-alt" })

    @Html.HiddenFor(model => model.FechaPago)
    <div class="content-box mrg20L mrg20R">
        <h3 class="content-box-header bg-default">
            <i class="glyph-icon icon-money"></i>
            Pago
            <div class="header-buttons-separator">
                <a href="#" class="icon-separator" onclick="$(this).parent().parent().parent().remove();">
                    <i class="glyph-icon icon-times font-red"></i>
                </a>
            </div>
        </h3>
        <div class="content-box-wrapper pago">

            <div class="col-xs-12 col-sm-3">
                <b>Fecha de Pago</b><br />
                @Html.DisplayFor(model => model.FechaPago)
                @Html.HiddenFor(model => model.FechaPago)
            </div>
            <div class="col-xs-12 col-sm-3">
                <b>Forma de Pago</b><br />
                @Html.DisplayFor(model => model.FormaPago)
                @Html.HiddenFor(model => model.FormaPago)
            </div>
            <div class="col-xs-12 col-sm-3">
                <b>Moneda</b><br />
                @Html.DisplayFor(model => model.Moneda)
                @Html.HiddenFor(model => model.Moneda)
            </div>
            <div class="col-xs-12 col-sm-3">
                <b>Tipo de Cambio</b><br />
                @Html.DisplayFor(model => model.TipoCambio)
                @Html.HiddenFor(model => model.TipoCambio)
            </div>
            <div class="col-xs-12 col-sm-3">
                <b>Monto</b><br />
                @Model.Monto.ToString("c")
                @*@Html.DisplayFor(model => model.Monto)*@
                @Html.HiddenFor(model => model.Monto)
            </div>
            <div class="col-xs-12 col-sm-3">
                <b>Número de Operación</b><br />
                @if (Model.NumeroOperacion != null || Model.NumeroOperacion == "")
                    {
                    @Html.DisplayFor(model => model.NumeroOperacion)
                    @Html.HiddenFor(model => model.NumeroOperacion)
                    }
                else
                    {
                    @Html.Raw("Sin Definir")
                    }
            </div>

            <div class="col-xs-12 col-sm-3">
                <b>Banco Ordenante</b><br />
                @if (Model.BancoOrdenanteId != null)
                    {
                    @Html.HiddenFor(model => model.BancoOrdenanteId)
                    @Html.DisplayFor(model => model.BancoOrdenante.Nombre)
                    @Html.HiddenFor(model => model.BancoOrdenante.Nombre)
                    @Html.HiddenFor(model => model.BancoOrdenante.BancoId)
                    @Html.HiddenFor(model => model.BancoOrdenante.Nombre)
                    @Html.HiddenFor(model => model.BancoOrdenante.Id)
                    @Html.HiddenFor(model => model.BancoOrdenante.NumeroCuenta)
                    @Html.HiddenFor(model => model.BancoOrdenante.ClienteId)

                    @Html.HiddenFor(model => model.BancoOrdenante.Banco.Id)
                    @Html.HiddenFor(model => model.BancoOrdenante.Banco.RazonSocial)
                    @Html.HiddenFor(model => model.BancoOrdenante.Banco.NombreCorto)
                    @Html.HiddenFor(model => model.BancoOrdenante.Banco.Rfc)
                    @Html.HiddenFor(model => model.BancoOrdenante.Banco.Status)
                    }
                else
                    {
                    @Html.Raw("Sin Definir")
                    }
            </div>

            <div class="col-xs-12 col-sm-3">
                <b>Banco Beneficiario</b><br />
                @if (Model.BancoBeneficiarioId != null)
                    {
                    @Html.HiddenFor(model => model.BancoBeneficiarioId)
                    @Html.DisplayFor(model => model.BancoBeneficiario.Nombre)
                    @Html.HiddenFor(model => model.BancoBeneficiario.Nombre)
                    @Html.HiddenFor(model => model.BancoBeneficiario.BancoId)
                    @Html.HiddenFor(model => model.BancoBeneficiario.SucursalId)
                    @Html.HiddenFor(model => model.BancoBeneficiario.NumeroCuenta)

                    @Html.HiddenFor(model => model.BancoBeneficiario.Banco.Id)
                    @Html.HiddenFor(model => model.BancoBeneficiario.Banco.RazonSocial)
                    @Html.HiddenFor(model => model.BancoBeneficiario.Banco.NombreCorto)
                    @Html.HiddenFor(model => model.BancoBeneficiario.Banco.Rfc)
                    @Html.HiddenFor(model => model.BancoBeneficiario.Banco.Status)
                    }
                else
                    {
                    @Html.Raw("Sin Definir")
                    }
            </div>

            @if (Model.TipoCadenaPago == CFDI.API.Enums.Complementos.Pagos10.c_TipoCadenaPago.Spei)
                {
                @Html.HiddenFor(model => model.TipoCadenaPago)

                <div class="clearfix"></div>

                <div class="sub-title">
                    <span class="fa fa-bars text-muted"></span> Información
                </div>

                <hr />

                <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <b>Cadena de Pago de SPEI</b><br />
                    @Html.DisplayFor(model => model.CadenaPago)
                    @Html.HiddenFor(model => model.CadenaPago)
                </div>

                <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <b>Certificado de Pago</b><br />
                    @Html.DisplayFor(model => model.CertificadoPago)
                    @Html.HiddenFor(model => model.CertificadoPago)
                </div>

                <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <b>Sello de Pago</b><br />
                    @Html.DisplayFor(model => model.SelloPago)
                    @Html.HiddenFor(model => model.SelloPago)
                </div>
                }



            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.SucursalId)

            <div class="clearfix"></div>
        </div>
    </div>
    }

APBox/Views/ComplementosPagos/_ComplementosPagosScripts.cshtml
<script>
    $(function () {
        $("#agregarDetalle").on('click', function () {
            $.ajax({
                type: 'POST',
                url: ' @Url.Action("AgregarPago", "AjaxOperaciones")',
                data: JSON.stringify({ fechaPago: $('#Pago_FechaPago').val(), formaPago: $('#Pago_FormaPago').val(), moneda: $('#Pago_Moneda').val(), tipoCambio: $('#Pago_TipoCambio').val(), monto: $('#Pago_Monto').val(), numeroOperacion: $('#Pago_NumeroOperacion').val(), tipoCadenaPago: $('#Pago_TipoCadenaPago').val(), certificadoPago: $('#Pago_CertificadoPago').val(), cadenaPago: $('#Pago_CadenaPago').val(), selloPago: $('#Pago_SelloPago').val(), spei: null, bancoEmisorId: $('#Pago_BancoOrdenanteId').val(), bancoReceptorId: $('#Pago_BancoBeneficiarioId').val() }),
                dataType: 'html',
                contentType: "application/json; charset=utf-8",
            }).success(function (partialView) {
                $('#detalles').append(partialView);
            })
                .fail(function (jqxhr, textStatus, error) {
                    alert("Favor de llenar todos los datos para los detalles");
                });
            return false;
        });
    });

    function agregarFactura() {
        $.ajax({
            type: 'POST',
            url: ' @Url.Action("AgregarFacturaComplementoPago", "AjaxOperaciones")',
            data: JSON.stringify({ pagoId: $('#PagoId').val(), facturaEmitidaId: $('#FacturaEmitidaId').val(), numeroParcialidad: $('#Pago_DocumentoRelacionado_NumeroParcialidad').val(), moneda: $('#Pago_DocumentoRelacionado_Moneda').val(), tipoCambio: $('#Pago_DocumentoRelacionado_TipoCambio').val(), importeSaldoAnterior: $('#Pago_DocumentoRelacionado_ImporteSaldoAnterior').val(), importePagado: $('#Pago_DocumentoRelacionado_ImportePagado').val(), importeSaldoInsoluto: $('#Pago_DocumentoRelacionado_ImporteSaldoInsoluto').val() }),
            dataType: 'html',
            contentType: "application/json; charset=utf-8",
        }).success(function (partialView) {
            $('#documento' + $('#PagoId').val()).append(partialView);
        })
            .fail(function (jqxhr, textStatus, error) {
                alert("Favor de seleccionar una factura");
            });
        return false;
    }

    $(function () {
        $('#ReceptorId').on('change', function () {
            var bancoSeleccionado = $('#Pago_BancoOrdenanteId');
            var cfdisCancelados = $('#CfdiRelacionadoId');

            var receptorSeleccionado = $(this);

            bancoSeleccionado.empty();
            cfdisCancelados.empty();
            //bancoSeleccionado.prop('disabled', '');


            bancoSeleccionado.append($('<option>', {
                text: "Sin seleccionar",
                value: null
            }));

            //cfdisCancelados.append($('<option>', {
            //    text: "Favor de hacer su selección",
            //    value: null
            //}));

            if (receptorSeleccionado.val().length > 0 && receptorSeleccionado.val() !== 0) {
                $.ajax({
                    type: 'POST',
                    url: ' @Url.Action("GetBancosClientes", "AjaxCatalogos")',
                    data: JSON.stringify({ clienteId: receptorSeleccionado.val() }),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        $.each(data, function (i, banco) {
                            bancoSeleccionado.append($('<option>', {
                                value: banco.Id,
                                text: banco.Nombre
                            }));
                        });
                        $('select').selectpicker('refresh');
                        return false;
                    }
                });


                $.ajax({
                    type: 'POST',
                    url: ' @Url.Action("GetCfdisCancelados", "AjaxCatalogos")',
                    data: JSON.stringify({ clienteId: receptorSeleccionado.val() }),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data2) {
                        $.each(data2, function (i, cfdi) {
                            cfdisCancelados.append($('<option>', {
                                value: cfdi.FacturaEmitida.Id,
                                text: cfdi.FacturaEmitida.Desplegado
                            }));
                        });
                        $('select').selectpicker('refresh');
                        return false;
                    }
                });
            }
        });
    });

    //JavaScript
    function getBase64(file) {
        var reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = function () {
            console.log(reader.result);
        };
        reader.onerror = function (error) {
            console.log('Error: ', error);
        };
    }
</script>