APBox/Controllers/Ajax/AjaxCatalogosController.cs
using APBox.Context;
using API.Models.Dto;
using API.Relaciones;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace InventorAid.Controllers.Ajax
{
    public class AjaxCatalogosController : Controller
    {

        #region Variables

        private readonly APBoxContext _db = new APBoxContext();

        #endregion

        public PartialViewResult SucursalesUsuarios(int sucursalId)
        {
            var usuarioSucursal = new UsuarioSucursal
            {
                SucursalId = sucursalId,
                Sucursal = _db.Sucursales.Find(sucursalId)
            };

            return PartialView("~/Views/Usuarios/Sucursales.cshtml", usuarioSucursal);
        }

        public PartialViewResult SucursalesProveedores(int sucursalId)
        {
            var proveedorSucursal = new ProveedorSucursal
            {
                SucursalId = sucursalId,
                Sucursal = _db.Sucursales.Find(sucursalId)
            };

            return PartialView("~/Views/Proveedores/Sucursales.cshtml", proveedorSucursal);
        }

        public PartialViewResult BancosClientes(int bancoId, string nombre, string numeroCuenta)
        {
            var bancoCliente = new BancoCliente
            {
                BancoId = bancoId,
                Banco = _db.Bancos.Find(bancoId),
                Nombre = nombre,
                NumeroCuenta = numeroCuenta
            };

            return PartialView("~/Views/Clientes/Bancos.cshtml", bancoCliente);
        }

        public PartialViewResult BancosSucursales(int bancoId, string nombre, string numeroCuenta)
        {
            var bancoSucursal = new BancoSucursal
            {
                BancoId = bancoId,
                Banco = _db.Bancos.Find(bancoId),
                Nombre = nombre,
                NumeroCuenta = numeroCuenta
            };

            return PartialView("~/Views/Sucursales/Bancos.cshtml", bancoSucursal);
        }

        #region Popular DropDowns

        public JsonResult GetSucursales(int grupoId)
        {
            var sucursales = _db.Sucursales.Where(s => s.GrupoId == grupoId).OrderBy(s => s.Nombre).ToList();

            foreach (var sucursal in sucursales)
            {
                sucursal.Grupo = null;

                if(sucursal.Bancos != null)
                {
                    sucursal.Bancos.Clear();
                    sucursal.Bancos = null;
                }
                sucursal.Banco = null;

                sucursal.ArchivoCer = null;
                sucursal.Cer = null;
                sucursal.ArchivoKey = null;
                sucursal.Key = null;
                sucursal.ArchivoLogo = null;
                sucursal.Logo = null;
            }

            return Json(sucursales, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBancosClientes(int clienteId)
        {
            var bancosClientes = _db.BancosClientes.Where(s => s.ClienteId == clienteId).OrderBy(s => s.Nombre).ToList();

            foreach (var banco in bancosClientes)
            {
                banco.Cliente.Sucursal = new API.Catalogos.Sucursal();
                
                if(banco.Cliente.Bancos != null)
                {
                    banco.Cliente.Bancos.Clear();
                    banco.Cliente.Bancos = null;
                }
            }

            return Json(bancosClientes, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCfdisCancelados(int clienteId)
        {
            var cfdis = _db.ComplementosPago.Where(f => f.ReceptorId == clienteId  && f.FacturaEmitidaId != null).ToList();

            foreach (var cfdi in cfdis)
            {

                cfdi.FacturaEmitida.ArchivoFisicoXml = null;
                cfdi.FacturaEmitida.CodigoQR = null;
                cfdi.FacturaEmitida.Emisor.Bancos.Clear();
                cfdi.FacturaEmitida.Emisor.Cer = null;
                cfdi.FacturaEmitida.Emisor.Key = null;
                cfdi.FacturaEmitida.Emisor.Grupo = null;
                cfdi.FacturaEmitida.Emisor.Logo = null;

                cfdi.FacturaEmitida.Receptor.Bancos.Clear();
                cfdi.FacturaEmitida.Receptor.Sucursal = null;

                cfdi.FacturaEmitida.CentroCosto = null;
                cfdi.FacturaEmitida.ComplementosPago.Clear();
                cfdi.FacturaEmitida.ComplementosPago = null;
                cfdi.FacturaEmitida.Departamento = null;

                cfdi.Pagos.Clear();
                cfdi.Pagos = null;
                cfdi.Receptor = null;
                cfdi.Sucursal = null;
            }

            return Json(cfdis, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCfdisCanceladosCP(int? clienteId)
        {
            var cfdis = _db.ComplementoCartaPortes.Where(f => f.ReceptorId == clienteId &&  f.FacturaEmitidaId != null && f.Total > 0).ToList();
            
            var ListCfdiR = new List<CfdiRelacionadoDto>();
            foreach (var cfdi in cfdis)
            {
                CfdiRelacionadoDto cfdiR = new CfdiRelacionadoDto 
                {
                    Id = cfdi.FacturaEmitida.Id,
                    Desplegado = cfdi.FacturaEmitida.Desplegado
                };
               
               
                ListCfdiR.Add(cfdiR);
            }
            
            return Json(ListCfdiR, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

APBox/Controllers/Catalogos/ClientesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using APBox.Context;
using API.Catalogos;
using System;
using APBox.Control;
using Aplicacion.LogicaPrincipal.Acondicionamientos.Catalogos;
using CFDI.API.Enums.CFDI33;

namespace APBox.Controllers.Catalogos
{
    [APBox.Control.SessionExpire]
    public class ClientesController : Controller
    {
        
        #region Variables

        private readonly APBoxContext _db = new APBoxContext();
        private readonly AcondicionarClientes _acondicionarClientes = new AcondicionarClientes();

        #endregion

        // GET: Clientes
        public ActionResult Index()
        {
            var sucursalId = ObtenerSucursal();
            var clientes = _db.Clientes.Where(c => c.SucursalId == sucursalId).ToList();
            return View(clientes);
        }

        // GET: Clientes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = _db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }

            PopulaForma();
            return View(cliente);
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            PopulaForma();

            var cliente = new Cliente
            {
                Status = API.Enums.Status.Activo,
                FechaAlta = DateTime.Now,
                Pais = c_Pais.MEX,
                SucursalId = ObtenerSucursal()
            };

            return View(cliente);
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cliente cliente)
        {
            ModelState.Remove("Banco.Id");
            ModelState.Remove("Banco.Nombre");
            ModelState.Remove("Banco.NumeroCuenta");

            if (ModelState.IsValid)
            {
                _acondicionarClientes.CargaInicial(ref cliente);

                _db.Clientes.Add(cliente);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            PopulaForma();
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = _db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }

            PopulaForma();

            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Cliente cliente)
        {
            ModelState.Remove("Banco.Id");
            ModelState.Remove("Banco.Nombre");
            ModelState.Remove("Banco.NumeroCuenta");

            if (ModelState.IsValid)
            {
                _acondicionarClientes.Bancos(cliente);

                _db.Entry(cliente).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            PopulaForma();
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = _db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            PopulaForma();
            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cliente cliente = _db.Clientes.Find(id);
            _db.Clientes.Remove(cliente);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region PopulaForma

        private int ObtenerGrupo()
        {
            return Convert.ToInt32(Session["GrupoId"]);
        }

        private int ObtenerSucursal()
        {
            return Convert.ToInt32(Session["SucursalId"]);
        }

        private void PopulaForma()
        {
            var popularDropDowns = new PopularDropDowns(ObtenerGrupo(), true);

            ViewBag.BancoId = popularDropDowns.PopulaBancos(null);
        }

        #endregion

    }
}

APBox/Controllers/Operaciones/CargasMasivasController.cs
using API.Models.Cargas;
using Aplicacion.LogicaPrincipal.CargasMasivas.Catalogos;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Mime;
using System.Web.Mvc;

namespace APBox.Controllers.Operaciones
{
    public class CargasMasivasController : Controller
    {

        #region Variables

        private readonly RelacionarBancosClientes _relacionarBancosClientes = new RelacionarBancosClientes();
        private readonly RelacionarBancosSucursales _relacionarBancosSucursales = new RelacionarBancosSucursales();

        #endregion

        // GET: CargasMasivas
        public ActionResult RelacionClientesBancos()
        {
            var cargasMasivasModel = new CargasMasivasModel
            {
                Prepopulado = true,
                SucursalId = ObtenerSucursal()
            };

            return View(cargasMasivasModel);
        }

        [HttpPost]
        public ActionResult RelacionClientesBancos(CargasMasivasModel cargasMasivasModel, string actionName)
        {
            if (ModelState.IsValid)
            {
                var errores = new List<String>();
                try
                {
                    switch (actionName)
                    {
                        case "Cargar":
                            var path = SubeArchivo();
                            errores = _relacionarBancosClientes.Importar(path, ObtenerSucursal());
                            if (errores.Count > 0)
                            {
                                foreach (var error in errores)
                                {
                                    ModelState.AddModelError("", error);
                                }
                            }
                            break;
                        case "Descargar":
                            var pathArchivo = _relacionarBancosClientes.Exportar(cargasMasivasModel.SucursalId, cargasMasivasModel.Prepopulado);
                            return File(pathArchivo, MediaTypeNames.Application.Octet, Path.GetFileName(pathArchivo));
                    }
                    if (errores.Count == 0)
                    {
                        ModelState.AddModelError("", "Comando realizado con éxito");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(cargasMasivasModel);
        }

        public ActionResult RelacionSucursalesBancos()
        {
            var cargasMasivasModel = new CargasMasivasModel
            {
                Prepopulado = true,
                SucursalId = ObtenerSucursal()
            };

            return View(cargasMasivasModel);
        }

        [HttpPost]
        public ActionResult RelacionSucursalesBancos(CargasMasivasModel cargasMasivasModel, string actionName)
        {
            if (ModelState.IsValid)
            {
                var errores = new List<String>();
                try
                {
                    switch (actionName)
                    {
                        case "Cargar":
                            var path = SubeArchivo();
                            errores = _relacionarBancosSucursales.Importar(path, ObtenerSucursal());
                            if (errores.Count > 0)
                            {
                                foreach (var error in errores)
                                {
                                    ModelState.AddModelError("", error);
                                }
                            }
                            break;
                        case "Descargar":
                            var pathArchivo = _relacionarBancosSucursales.Exportar(cargasMasivasModel.SucursalId, cargasMasivasModel.Prepopulado);
                            return File(pathArchivo, MediaTypeNames.Application.Octet, Path.GetFileName(pathArchivo));
                    }
                    if (errores.Count == 0)
                    {
                        ModelState.AddModelError("", "Comando realizado con éxito");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(cargasMasivasModel);
        }

        #region Popula Forma

        private int ObtenerSucursal()
        {
            return Convert.ToInt32(Session["SucursalId"]);
        }

        #endregion

        #region Archivos

        private String SubeArchivo()
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    try
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Archivos/CargasMasivas/"), fileName);
                        file.SaveAs(path);
                        return path;
                    }
                    catch (Exception)
                    {
                    }

                }
            }
            return null;
        }

        #endregion

    }
}

APBox/Views/Clientes/Edit.cshtml
@model API.Catalogos.Cliente

@{
    ViewBag.Title = "Editar";
    ViewBag.Clase = "Cliente";
}

<script>
    $(function () {
        $("#agregarBanco").on('click', function () {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("BancosClientes", "AjaxCatalogos")',
                data: JSON.stringify({ bancoId: $('#BancoId').val(), nombre: $('#Banco_Nombre').val(), numeroCuenta: $('#Banco_NumeroCuenta').val() }),
                dataType: 'html',
                contentType: "application/json; charset=utf-8",
            }).success(function (partialView) {
                $('#bancos').append(partialView);
                return false;
            })
                .fail(function (jqxhr, textStatus, error) {
                    alert("Favor de llenar todos los datos para los detalles");
                    return false;
                });
            return false;
        });
    });
</script>

<div id="page-title">
    <h2>@ViewBag.Title @ViewBag.Clase</h2>
</div>

<div class="panel">
    <div class="panel-body">
        <h3 class="title-hero">
            Información
        </h3>
        <div class="row">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.FechaAlta)
                @Html.HiddenFor(model => model.SucursalId)

            <div class="form">
                @Html.ValidationSummary(true, "", new { @class = "label-blue-alt" })

                <div class="form-group col-xs-12">
                    <h2>
                        @Html.DisplayFor(model => model.RazonSocial)
                    </h2>
                </div>

                <div class="clearfix"></div>
                <hr />

                <div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-6">
                    @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-6">
                    @Html.LabelFor(model => model.Rfc, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Rfc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Rfc, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-xs-12 col-lg-3">
                    @Html.LabelFor(model => model.CodigoPostal, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.CodigoPostal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CodigoPostal, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-xs-12 col-lg-3">
                    @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label" })
                    @Html.EnumDropDownListSpecialFor(model => model.Pais)
                    @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-xs-12 col-lg-3">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
                    @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-xs-12 col-lg-3">
                    @Html.LabelFor(model => model.NumRegIdTrib, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.NumRegIdTrib, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NumRegIdTrib, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-xs-12 col-lg-3">
                    @Html.LabelFor(model => model.UsoCfdi, htmlAttributes: new { @class = "control-label" })
                    @Html.EnumDropDownListFor(model => model.UsoCfdi, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UsoCfdi, "", new { @class = "text-danger" })
                </div>

                <div class="clearfix"></div>

                <div class="form-group col-xs-12 col-lg-3">
                    @Html.LabelFor(model => model.Telefono1, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Telefono1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefono1, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-xs-12 col-lg-3">
                    @Html.LabelFor(model => model.Telefono2, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Telefono2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefono2, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-xs-12 col-lg-6">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label" })
                    @Html.TextAreaFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
                </div>

                <div class="clearfix"></div>
                <hr />

                <div class="col-sm-10 col-sm-offset-1">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Bancos
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="form-group col-lg-5">
                                    @Html.LabelFor(model => model.Banco.BancoId, htmlAttributes: new { @class = "control-label" })
                                    @Html.DropDownList("BancoId", null, "Favor de hacer su selección", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Banco.BancoId, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-lg-3">
                                    @Html.LabelFor(model => model.Banco.Nombre, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.Banco.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Banco.Nombre, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-lg-3">
                                    @Html.LabelFor(model => model.Banco.NumeroCuenta, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.Banco.NumeroCuenta, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Banco.NumeroCuenta, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-lg-1">
                                    <label class="control-label">Agregar</label> <br />
                                    <div id="agregarBanco" style="cursor:pointer">
                                        <span class="fa fa-plus-circle fa-2x text-success"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="clearfix"></div>

                            <div class="col-xs-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        Bancos Asignados
                                    </div>
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-lg-5">
                                                <b>Banco</b>
                                            </div>
                                            <div class="col-lg-3">
                                                <b>Nombre</b>
                                            </div>
                                            <div class="col-lg-3">
                                                <b>Número de Cuenta</b>
                                            </div>
                                            <div class="col-lg-1">
                                                <b></b>
                                            </div>
                                        </div>
                                        <div>
                                            <div id="bancos">
                                                @if (Model.Bancos != null)
                                                {
                                                    foreach (var banco in Model.Bancos)
                                                    {
                                @Html.Partial("~/Views/Clientes/Bancos.cshtml", banco)}
                                                }
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>

                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>


                <div class="clearfix"></div>
                <hr />

                <div class="form-group pull-right">
                    <button type="button" class="btn btn-alt btn-hover btn-default" onclick="location.href='@Url.Action("Index", "Clientes")';">
                        <span>Regresar</span>
                        <i class="glyph-icon icon-arrow-left"></i>
                    </button>
                    <button type="submit" class="btn btn-alt btn-hover btn-blue-alt">
                        <span>Guardar</span>
                        <i class="glyph-icon icon-arrow-right"></i>
                    </button>
                </div>

            </div>
            }
        </div>
    </div>
</div>

APBox/Views/Clientes/Index.cshtml
@model IEnumerable<API.Catalogos.Cliente>

@{
    ViewBag.Title = "Clientes";
}

<div id="page-title">
    <div class="row">
        <div class="col-lg-9">
            <h2>Clientes</h2>
            <p>Puedes asignar los bancos y cambiar datos de la información del cliente. Los clientes se crean automáticamente.</p>
        </div>
        <div class="col-lg-3">
            <button type="submit" class="btn btn-alt btn-hover btn-primary float-right" onclick="location.href='@Url.Action("Create", "Clientes")';return false;">
                <span>Nuevo Cliente</span>
                <i class="glyph-icon icon-arrow-right"></i>
            </button>
            <button type="submit" class="btn btn-alt btn-hover btn-primary float-right" onclick="location.href='@Url.Action("RelacionClientesBancos", "CargasMasivas")';return false;">
                <span>Bancos por Layout</span>
                <i class="glyph-icon icon-arrow-right"></i>
            </button>
        </div>
    </div>
</div>

<div class="panel">
    <div class="panel-body">
        <div class="row">
            <table class="table table-condensed dataTable" data-columna="0" data-orden="asc">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.RazonSocial)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Rfc)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FechaAlta)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Status)
                        </th>
                        <th>
                            Opciones
                        </th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.RazonSocial)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Rfc)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaAlta)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="fa fa-cog"></span> Opciones
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li>@Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "edit" })</li>
                                        <li>@Html.ActionLink("Detalles", "Details", new { id = item.Id }, new { @class = "details" })</li>
                                        <li>@Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "delete" })</li>
                                    </ul>
                                </div>
                            </td>

                        </tr>
                        }
                </tbody>
            </table>
        </div>
    </div>
</div>